
import { PracticeRequest } from "../types";

export const generateMockScript = (request: PracticeRequest): string => {
  // This is a placeholder - in a real implementation, this would be generated by an LLM or from templates
  return `
  [Introduction - 1 minute]
  Find a comfortable position, either seated or lying down. Allow your body to settle and your breath to come naturally. 
  As we begin this ${request.duration}-minute practice focused on ${request.focusAreas.join(", ")}, 
  bring your attention to the present moment.
  
  [Body Scan - 2 minutes]
  Bring awareness to your body, starting from the top of your head and moving slowly down to your toes.
  Notice any areas of tension or discomfort without judgment.
  As an introvert, you may notice that certain parts of your body hold tension from social interactions or deep thinking.
  
  [Core Practice - ${request.duration - 5} minutes]
  ${request.focusAreas.includes("Social Recovery") ? 
    "Imagine a protective sphere of energy surrounding you, filtering out external stimulation and creating a space that's just for you. With each breath, feel this sphere becoming stronger and more nurturing." : ""}
  ${request.focusAreas.includes("Energy Conservation") ? 
    "Visualize your energy as a precious resource, a gentle glowing light within you. Notice how this light naturally wants to be directed inward, nourishing your inner world rather than being scattered outward." : ""}
  ${request.focusAreas.includes("Quiet Strength") ? 
    "Connect with the deep well of wisdom that comes from your introvert nature - the ability to observe, to listen, to process deeply. Feel the strength that comes from this thoughtful approach to the world." : ""}
  ${request.situationDetails ? 
    `As you continue breathing deeply, bring to mind the situation you described: ${request.situationDetails}. Notice any sensations or emotions that arise without judgment.` : ""}
  
  [Closing - 2 minutes]
  Gradually begin to deepen your breath, gently wiggling your fingers and toes.
  When you're ready, slowly open your eyes, carrying this sense of ${request.focusAreas[0]?.toLowerCase() || "calm"} with you.
  Remember that you can return to this practice whenever you need to reconnect with your introvert strengths.
  `;
};
