#!/bin/bash

# Script to generate RevenueCat stub Swift files
# These files will be used in Xcode Cloud builds to avoid the "Build input files cannot be found" error

STUBS_DIR="revenuecat_stubs/Sources"

# Template for the stub Swift files
STUB_CONTENT='// Stub file created for build compatibility
import Foundation
// Empty implementation to satisfy the compiler
// Real implementation will be loaded from the framework at runtime
'

# Function to create a stub Swift file
create_stub_file() {
  local file_path="$1"
  mkdir -p "$(dirname "$file_path")"
  echo "$STUB_CONTENT" > "$file_path"
  echo "Created: $file_path"
}

# Create all the RevenueCat stub files
create_stub_file "$STUBS_DIR/Attribution/ASIdManagerProxy.swift"
create_stub_file "$STUBS_DIR/Error Handling/Assertions.swift"
create_stub_file "$STUBS_DIR/Attribution/AttributionData.swift"
create_stub_file "$STUBS_DIR/Attribution/AttributionFetcher.swift"
create_stub_file "$STUBS_DIR/Attribution/AttributionNetwork.swift"
create_stub_file "$STUBS_DIR/Attribution/AttributionPoster.swift"
create_stub_file "$STUBS_DIR/Attribution/AttributionTypeFactory.swift"
create_stub_file "$STUBS_DIR/Error Handling/BackendError.swift"
create_stub_file "$STUBS_DIR/Error Handling/BackendErrorCode.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/Background.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/Border.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/ComponentOverrides.swift"
create_stub_file "$STUBS_DIR/Networking/CustomerCenterConfigAPI.swift"
create_stub_file "$STUBS_DIR/Networking/Caching/CustomerCenterConfigCallback.swift"
create_stub_file "$STUBS_DIR/CustomerCenter/CustomerCenterConfigData.swift"
create_stub_file "$STUBS_DIR/Networking/Responses/CustomerCenterConfigResponse.swift"
create_stub_file "$STUBS_DIR/CustomerCenter/Events/CustomerCenterEvent.swift"
create_stub_file "$STUBS_DIR/CustomerCenter/CustomerCenterPresentationMode.swift"
create_stub_file "$STUBS_DIR/Identity/CustomerInfo.swift"
create_stub_file "$STUBS_DIR/Identity/CustomerInfo+ActiveDates.swift"
create_stub_file "$STUBS_DIR/Identity/CustomerInfo+NonSubscriptions.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift"
create_stub_file "$STUBS_DIR/Identity/CustomerInfoManager.swift"
create_stub_file "$STUBS_DIR/DeepLink/DeepLinkParser.swift"
create_stub_file "$STUBS_DIR/Error Handling/DescribableError.swift"
create_stub_file "$STUBS_DIR/Caching/DeviceCache.swift"
create_stub_file "$STUBS_DIR/Diagnostics/DiagnosticsEvent.swift"
create_stub_file "$STUBS_DIR/Diagnostics/Networking/DiagnosticsEventsRequest.swift"
create_stub_file "$STUBS_DIR/Diagnostics/DiagnosticsFileHandler.swift"
create_stub_file "$STUBS_DIR/Diagnostics/Networking/DiagnosticsHTTPRequestPath.swift"
create_stub_file "$STUBS_DIR/Diagnostics/Networking/DiagnosticsPostOperation.swift"
create_stub_file "$STUBS_DIR/Diagnostics/Networking/DiagnosticsSynchronizer.swift"
create_stub_file "$STUBS_DIR/Diagnostics/DiagnosticsTracker.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/Dimension.swift"
create_stub_file "$STUBS_DIR/DocCDocumentation/EmptyFile.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKitAbstractions/EncodedAppleReceipt.swift"
create_stub_file "$STUBS_DIR/Error Handling/ErrorCode.swift"
create_stub_file "$STUBS_DIR/Error Handling/ErrorDetails.swift"
create_stub_file "$STUBS_DIR/Error Handling/ErrorUtils.swift"
create_stub_file "$STUBS_DIR/Events/Networking/EventsRequest.swift"
create_stub_file "$STUBS_DIR/CustomerCenter/Events/EventsRequest+CustomerCenter.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/Networking/EventsRequest+Paywall.swift"
create_stub_file "$STUBS_DIR/Events/FeatureEvent.swift"
create_stub_file "$STUBS_DIR/Diagnostics/FileHandler.swift"
create_stub_file "$STUBS_DIR/Networking/Operations/GetCustomerCenterConfigOperation.swift"
create_stub_file "$STUBS_DIR/Security/HTTPRequest+Signing.swift"
create_stub_file "$STUBS_DIR/Identity/IdentityManager.swift"
create_stub_file "$STUBS_DIR/Caching/InMemoryCachedObject.swift"
create_stub_file "$STUBS_DIR/Misc/DateAndTime/ISODurationFormatter.swift"
create_stub_file "$STUBS_DIR/LocalReceiptParsing/LocalReceiptFetcher.swift"
create_stub_file "$STUBS_DIR/Misc/MapAppStoreDetector.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/OfflineCustomerInfoCreator.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/OfflineEntitlementsManager.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallButtonComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/PaywallCacheWarming.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallCarouselComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/PaywallColor.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/PaywallComponentBase.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/PaywallComponentLocalization.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift"
create_stub_file "$STUBS_DIR/Networking/Responses/RevenueCatUI/PaywallComponentsData.swift"
create_stub_file "$STUBS_DIR/Paywalls/PaywallData.swift"
create_stub_file "$STUBS_DIR/Paywalls/PaywallData+Localization.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/PaywallEvent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/PaywallEventsManager.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/PaywallEventStore.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/Networking/PaywallHttpRequestPath.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallIconComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallImageComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallPackageComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallPurchaseButtonComponent.swift"
create_stub_file "$STUBS_DIR/Logging/Strings/PaywallsStrings.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallStackComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallStickyFooterComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallTabsComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallTextComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallTimelineComponent.swift"
create_stub_file "$STUBS_DIR/Paywalls/Components/PaywallV2CacheWarming.swift"
create_stub_file "$STUBS_DIR/Paywalls/PaywallViewMode.swift"
create_stub_file "$STUBS_DIR/CodableExtensions/PeriodType+Extensions.swift"
create_stub_file "$STUBS_DIR/Paywalls/Events/Networking/PostPaywallEventsOperation.swift"
create_stub_file "$STUBS_DIR/Networking/Operations/PostRedeemWebPurchaseOperation.swift"
create_stub_file "$STUBS_DIR/Misc/Locale/PreferredLocalesProvider.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/ProductEntitlementMapping.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/ProductEntitlementMappingFetcher.swift"
create_stub_file "$STUBS_DIR/Identity/ProductPaidPrice.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/PurchasedProductsFetcher.swift"
create_stub_file "$STUBS_DIR/OfflineEntitlements/PurchasedSK2Product.swift"
create_stub_file "$STUBS_DIR/CodableExtensions/PurchaseOwnershipType+Extensions.swift"
create_stub_file "$STUBS_DIR/Purchasing/Purchases/PurchaseParams.swift"
create_stub_file "$STUBS_DIR/Purchasing/Purchases/PurchasesAreCompletedBy.swift"
create_stub_file "$STUBS_DIR/Error Handling/PurchasesError.swift"
create_stub_file "$STUBS_DIR/Misc/RateLimiter.swift"
create_stub_file "$STUBS_DIR/Networking/RedeemWebPurchaseAPI.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/SK2AppTransaction.swift"
create_stub_file "$STUBS_DIR/Error Handling/SKError+Extensions.swift"
create_stub_file "$STUBS_DIR/CodableExtensions/Store+Extensions.swift"
create_stub_file "$STUBS_DIR/Events/StoredEvent.swift"
create_stub_file "$STUBS_DIR/Events/StoredEventSerializer.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKitAbstractions/StoreEnvironment.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKitAbstractions/StorefrontProvider.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/Observer Mode/StoreKit2ObserverModePurchaseDetector.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/StoreKit2Receipt.swift"
create_stub_file "$STUBS_DIR/Error Handling/StoreKitError+Extensions.swift"
create_stub_file "$STUBS_DIR/Error Handling/StoreKitErrorHelper.swift"
create_stub_file "$STUBS_DIR/Misc/StoreKitVersion.swift"
create_stub_file "$STUBS_DIR/Support/StoreMessagesHelper.swift"
create_stub_file "$STUBS_DIR/Support/StoreMessageType.swift"
create_stub_file "$STUBS_DIR/Identity/SubscriptionInfo.swift"
create_stub_file "$STUBS_DIR/FoundationExtensions/TimeInterval+Extensions.swift"
create_stub_file "$STUBS_DIR/Attribution/TrackingManagerProxy.swift"
create_stub_file "$STUBS_DIR/Networking/Responses/RevenueCatUI/UIConfig.swift"
create_stub_file "$STUBS_DIR/WebPurchaseRedemption/URL+WebPurchaseRedemption.swift"
create_stub_file "$STUBS_DIR/WebPurchaseRedemption/WebPurchaseRedemption.swift"
create_stub_file "$STUBS_DIR/WebPurchaseRedemption/WebPurchaseRedemptionHelper.swift"
create_stub_file "$STUBS_DIR/WebPurchaseRedemption/WebPurchaseRedemptionResult.swift"
create_stub_file "$STUBS_DIR/Logging/Strings/WebRedemptionStrings.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKitAbstractions/WinBackOffer.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/Win-Back Offers/WinBackOfferEligibilityCalculator.swift"
create_stub_file "$STUBS_DIR/Purchasing/StoreKit2/Win-Back Offers/WinBackOfferEligibilityCalculatorType.swift"

echo "✅ Created all RevenueCat stub files in $STUBS_DIR"
echo "Total files created: $(find "$STUBS_DIR" -name "*.swift" | wc -l)"