
# Netlify configuration file
[build]
  # Directory to publish (SPA apps build to dist/ folder by default)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and headers

# Specific redirects for auth callbacks
[[redirects]]
  from = "/auth/callback/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/v1/callback/*"
  to = "/index.html"
  status = 200

# General SPA redirect (should be after more specific redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special redirect for Apple App Site Association file
[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true
  headers = {Content-Type = "application/json"}

# Headers to ensure proper content type for AASA file
[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

# Environment variables can be set here for development, or in the Netlify UI for production
[build.environment]
  NODE_VERSION = "18"
