
# Netlify configuration file
[build]
  # Directory to publish (SPA apps build to dist/ folder by default)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and headers
[[redirects]]
  # For single page applications, ensure routes are handled by index.html
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables can be set here for development, or in the Netlify UI for production
[build.environment]
  NODE_VERSION = "18"
